/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  safelist: [
    "bg-type-normal",
    "bg-type-fire",
    "bg-type-water",
    "bg-type-grass",
    "bg-type-electric",
    "bg-type-ice",
    "bg-type-fighting",
    "bg-type-poison",
    "bg-type-ground",
    "bg-type-flying",
    "bg-type-psychic",
    "bg-type-bug",
    "bg-type-rock",
    "bg-type-ghost",
    "bg-type-dark",
    "bg-type-dragon",
    "bg-type-steel",
    "bg-type-fairy",
    "bg-type-stellar",
    "bg-type-unknown",
    "bg-type-shadow",
    "bg-type-all",
    "text-type-normal",
    "text-type-fire",
    "text-type-water",
    "text-type-grass",
    "text-type-electric",
    "text-type-ice",
    "text-type-fighting",
    "text-type-poison",
    "text-type-ground",
    "text-type-flying",
    "text-type-psychic",
    "text-type-bug",
    "text-type-rock",
    "text-type-ghost",
    "text-type-dark",
    "text-type-dragon",
    "text-type-steel",
    "text-type-fairy",
    "text-type-stellar",
    "text-type-unknown",
    "text-type-shadow",
    "text-type-all",
    "text-black",
    "text-white",
  ],
  theme: {
    extend: {
      colors: {
        "header-bg": "#8FA9BE",
        "main-bg": "#B7D0E1",
        "type-normal": "#AAB09F",
        "type-fire": "#EA7A3C",
        "type-water": "#539AE2",
        "type-grass": "#71C558",
        "type-electric": "#E5C531",
        "type-ice": "#70CBD4",
        "type-fighting": "#CB5F48",
        "type-poison": "#B468B7",
        "type-ground": "#CC9F4F",
        "type-flying": "#7DA6DE",
        "type-psychic": "#E5709B",
        "type-bug": "#94BC4A",
        "type-rock": "#B2A061",
        "type-ghost": "#846AB6",
        "type-dark": "#736C75",
        "type-dragon": "#6A7BAF",
        "type-steel": "#89A1B0",
        "type-fairy": "#E397D1",
        "type-stellar": "#9FB5CE",
        "type-unknown": "#A9A9A9",
        "type-shadow": "#3B3A3A",
        "type-all": "#FFFFFF",
      },
    },
  },
  plugins: [],
};
